name: 编译内核 6.14.0 (含中文支持)

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      config:
        description: '配置文件'
        required: true
        default: 'linuxmint-config'
        type: string
      clean:
        description: '是否清理'
        required: true
        type: boolean
      deb:
        description: '打包为deb'
        type: boolean

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    env:
      LANG: zh_CN.UTF-8
      LANGUAGE: zh_CN:zh
      LC_ALL: zh_CN.UTF-8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: 启用源码源
        run: sudo mv sources.list /etc/apt/sources.list

      - name: 汉化
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-zh-hans

      - name: 清理空间
        if: ${{ inputs.clean }}
        uses: rokibhasansagar/slimhub_actions@main

      - name: 配置显示
        run: |
          echo "警告⚠"
          echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
          echo -e "已知CPU型号(降序): 7763，8370C，8272CL，8171M，E5-2673\n"
          echo "--------------------------CPU信息--------------------------"
          echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
          echo "CPU核心数量: $(nproc)"
          echo -e "CPU型号信息:$(cat /proc/cpuinfo | grep -m1 name | awk -F: '{print $2}')\n"
          echo "--------------------------内存信息--------------------------"
          echo "已安装内存详细信息:"
          echo -e "$(sudo lshw -short -C memory | grep GiB)\n"
          echo "--------------------------硬盘信息--------------------------"
          echo "硬盘数量: $(ls /dev/sd* | grep -v [1-9] | wc -l)" && df -hT

      - name: 安装依赖
        continue-on-error: true
        run: |
          sudo apt update
          sudo apt-get install build-essential libncurses-dev xz-utils libssl-dev flex libelf-dev bison fakeroot debhelper-compat=12 libdw-dev bc ccache pkg-config dpkg-dev
          sudo apt-get install openssl=3.0.13-0ubuntu3.6

      - name: 下载 linux 内核源码
        run: |
          git clone https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git --depth=1 --single-branch -b v6.14
      
      - name: 移动配置文件
        run: cp ${{ inputs.config }} linux/.config

      - name: 中文补丁
        run: |
          cd linux
          wget https://raw.githubusercontent.com/bigshans/cjktty-patches/refs/heads/master/v6.x/cjktty-6.9.patch
          patch -Np1 < ./cjktty-6.9.patch

      #- name: 禁用签名证书
      #  run: rm -f linux/certs/*pem

      - name: 编译 deb
        if: ${{ inputs.deb }}
        run: |
          cd linux
          git config --global user.email "actions@github.com"
          git config --global user.name "actions-bot"
          git add .
          git commit -m "cjktty"
          export ARCH=x86_64
          make -j$(nproc) deb-pkg
      
      - name: 编译
        if: ${{ !inputs.deb }}
        run: |
          cd linux
          export ARCH=x86_64
          make -j$(nproc)

      #- name: 移动
      #  run: mv *.deb build/*.deb

      - name: 上传
        if: ${{ inputs.deb }}
        uses: actions/upload-artifact@v4
        with:
          name: linuxmint-linux
          path: |
            *.deb
      
      - name: 自动发布发行版
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ inputs.config }}-6.14
          tag_name: ${{ inputs.config }}-6.14
          draft: false
          make_latest: true
          files: |
            *.deb