# This is a basic workflow to help you get started with Actions

name: 编译内核

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    env:
      LANG: zh_CN.UTF-8
      LANGUAGE: zh_CN:zh
      LC_ALL: zh_CN.UTF-8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: 启用源码源
        run: sudo mv sources.list /etc/apt/sources.list

      - name: 汉化
        run: |
          sudo apt-get update
          sudo apt-get install -y language-pack-zh-hans

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y git fakeroot build-essential ncurses-dev xz-utils libssl-dev bc flex libelf-dev bison dwarves zstd
          sudo apt-get build-dep linux

      - name: 下载 linux 内核源码
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          ref: v6.1
          path: linux
      
      - name: 移动配置文件
        run: cp config linux/.config

      - name: 中文补丁
        run: |
          cd linux
          wget https://raw.githubusercontent.com/zhmars/cjktty-patches/refs/heads/master/v6.x/cjktty-6.1.patch
          patch -Np1 < ./cjktty-6.1.patch

      - name: 编译
        run: |
          cd linux
          make -j$(nproc) deb-pkg

      - name: 移动
        run: mv *.deb build/*.deb

      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build
