# This is a basic workflow to help you get started with Actions

name: 编译内核

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  #push:
    #branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      LANG: zh_CN.UTF-8

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: 下载 linux 内核源码
        uses: actions/checkout@v4
        with:
          repository: torvalds/linux
          ref: v6.1
          path: linux

      - name: add deb-src to sources.list
        run: sudo sed -i "/deb-src/s/# //g" /etc/apt/sources.list

      - name: 安装依赖
        run: |
          sudo apt update
          sudo apt install -y wget xz-utils make gcc flex bison dpkg-dev bc rsync kmod cpio libssl-dev language-pack-zh-hans
          sudo apt build-dep -y linux
      
      - name: 移动配置文件
        run: cp config linux/.config

      - name: 中文补丁
        run: |
          cd linux
          wget https://raw.githubusercontent.com/zhmars/cjktty-patches/refs/heads/master/v6.x/cjktty-6.1.patch
          patch -Np1 < ./cjktty-6.1.patch

      - name: 编译
        run: |
          cd linux
          CPU_CORES=$(($(grep -c processor < /proc/cpuinfo)*2))
          make deb-pkg -j"$CPU_CORES"

      - name: 移动
        run: mv *.deb build/*.deb

      - name: 上传
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build
